_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 128
data_path:
    value: /data/data.pickle
embedding_dim:
    value: 95
hidden_dim:
    value: 230
init_value_z:
    value: 9.5
lr_main:
    value: 0.002
lr_z:
    value: 0.0004
model_version:
    value: v1
mom_main:
    value: 0.9
mom_z:
    value: 0.9
num_epochs:
    value: 400
